### ISSUE TITLE
Code of data_filter 

### ISSUE THREAD

**Issue by roger199805** [vu-minh/tsne-constraints#5]
@vu-minh Hi, I'm currently reading the paper "Constraint Preserving Score for Automatic Hyperparameter Tuning of Dimensionality Reduction Methods for Visualization" and I want to implement this paper, is it possible to ask for the code of data_filter to compute Q and constraint_score ? Thank you.

**Comment by roger199805** [comment]
> I'm currently reading the paper "Constraint Preserving Score for Automatic Hyperparameter Tuning of Dimensionality Reduction Methods for Visualization" and I want to implement this paper, is it possible to ask for the code of data_filter to compute Q and constraint_score ? Thank you.

**Comment by vu-minh** [comment]
Hi,

You can find more detail about my implementation in this repo: https://github.com/vu-minh/bo-constraint-score

The matrix `Q` and the `qij_based` score are computed in themodule [constraint_score.py](https://github.com/vu-minh/bo-constraint-score/blob/master/code/constraint_score.py), which will be called from this script [run_score.py](https://github.com/vu-minh/bo-constraint-score/blob/master/code/run_score.py).

In the above file `constraint_score.py`, you can also find the implementation of another kind of score (contrastive score). New kind of contrastive score is not presented in the current paper, it's our ongoing work.

To reproduce the figures in my paper, you can look at this script ([run_workflow.sh](https://github.com/vu-minh/bo-constraint-score/blob/master/code/run_workflow.sh) to see which code should be run to produce the corresponding figure.

Hope this helps!
